### ISSUE TITLE
leaks

### ISSUE THREAD

**Issue by ghost** [JongeunKeum/42born2code-push_swap#1]
leaks ./push_swap 3 2 1.   or leaks ./push_swap 6 5 4 3 2 1.   ......    one list is not correctly free

**Comment by jkeum-dev** [comment]
That's something I didn't know at all. Thank you for letting me know. 😊 I'll fix it!!

**Comment by ghost** [comment]
I did a case for a reverse sequense (9 8 7....2 1), it 's better to create a function 
`if (is_reverse_sorted(a))`
`{`
	`while (!is_sorted(a))`
	`{`
    	`rra algorithm`
	`}`
	`free_all(a, b);`
	`return (0);`
`}`
it's 3x faster

**Comment by ghost** [comment]
Ok I solved it [https://drive.google.com/drive/folders/1OBVi_ORXhQ6xD0NM883E5B72piD5belJ?usp=sharing](url)

in swap.c file, a link was missing. 
I also replace your GNL to a better version

**Comment by jkeum-dev** [comment]
In fact, I couldn't solve it.
There is also a leak when sorting backwards, but ./push_swap 6 5 4 2 1 3 also leaks memory in this case.
./push_swap 6 5 4 2 1 7 In this case, there is no leak, but in the above case, it was strange that there was a leak.

I didn't know there was a problem with the function in the operations folder.
If I had written something wrong there, I thought the sorting wouldn't be right.

I'll fix the code and push it soon.
And also I will study the GNL files you uploaded. Thanks for solving it. :)

**Comment by ghost** [comment]
Double linked list are hard top use . When I was sorting "3 2 1" , result where "sa,rra ", but when I used printf to see the result ,I only had" 1 2 ". 3 was Lost . So a link was missing in the list

**Comment by jkeum-dev** [comment]
It really is. But how did the results come out? It's weird...

I thought implementing the code with a double linked list would be a good fit for this project, but it was definitely difficult at first. I thought the nodes were connected well, but it wasn't.

I learned a lot thanks. :)
