### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by ghost** [JongeunKeum/42born2code-push_swap#2]
`➜   ./push_swap ""      
[1]    3827 segmentation fault  ./push_swap ""
➜  ./push_swap " "
[1]    5023 segmentation fault  ./push_swap " "`

error management when push swap receive only 2 quote, or 2 quote with space, , is like an argument but an empty argument

**Comment by jkeum-dev** [comment]
It is assumed that no white space is entered in the number input as an argument.
For this reason, exception handling may not be perfect..!
However, the segfault is dangerous, so I will fix it soon.
This is also an issue I hadn't thought of because I didn't check it. Thank you :)

**Comment by ghost** [comment]
./push_swap "" SEGFAULT
./push_swap "" "" SEGFAULT
./push_swap " "  SEGFAULT(space and tabs)
...
./push_swap "" 2 1 OK
./push_swap "" "" 2 1 OK
./push_swap "" "" 1 OK
...

so just to create a function if all arguments are emptry, or have space and tavb(is_space function)
If 1 number is present, it's ok , it return the error message

**Comment by cstpka** [comment]
ok My made a preview . can you test this ?
[https://drive.google.com/file/d/1L8tKFqRxGUC_w1FwFQdiboZh_1KvAR9H/view?usp=sharing](url)

**Comment by jkeum-dev** [comment]
In init_stack() to ft_split(), the arguments that are enclosed in double quotation marks are separated based on spaces, there was a problem.
There's a double pointer received by ft_split(), but there is nothing in it.
However, when I try to access the 0th, a seg-fault seems to occur.

`arg = ft_split();`
After this, I fixed the condition from `if (!arg)` to `if (!arg || !*arg)`.

**Comment by ghost** [comment]
it's working with with code, there is some bugs (./push_swap "" 3 2 does'nt return anything) but no segfault anymore    [main.txt](https://github.com/JongeunKeum/42born2code-push_swap/files/6752548/main.txt)
but it's alos working with what you did in init stack
